//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;



    public partial class user
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Required UserName")]
        public string Username { get; set; }


        [Required(ErrorMessage ="Required Password")]
        [DataType(DataType.Password)]   
        public string Password { get; set; }
        
        
        [DataType(DataType.Password)]
        [DisplayName("ConfirmPassword")] 
        [Compare("Password")]
        public String ConfirmPassword { get; set; }

       
        public Nullable<bool> IsAdmin { get; set; }
    }
}
